Added database structure
htmlacademy-php/1418273-readme-12 pull request #7
Opened 2020-06-02 18:23 UTC by mikhail7275

2020-06-04 13:52 UTC, VikingBO commented on schema.sql
> +CREATE TABLE `roles` (
Пункт 6 технического задания подразумевает просто наличие правила при котором незарегистрированные пользователи видят только главную страницу и могут только зарегистрироваться или авторизоваться, это ни как не влияет на разделение пользователей и наличие таблицы roles, хотя согласен что она по логике напрашивается, но нас в данном проекте никто не просил разделения пользователей по ролям, поэтому нужно убрать эту таблицу.

2020-06-04 15:11 UTC, VikingBO commented on schema.sql
> +    FOREIGN KEY (`hashtag`) REFERENCES `hashtags` (`id`) ON DELETE CASCADE
DELETE CASCADE насколько я помню удаляет по внешнему ключу связанные записи, разве нам это будет удобно если мы захотим удалить запись?

2020-06-04 16:59 UTC, mikhail7275 commented on schema.sql
> +CREATE TABLE `roles` (
ок

2020-06-04 17:40 UTC, mikhail7275 commented on schema.sql
> +    FOREIGN KEY (`hashtag`) REFERENCES `hashtags` (`id`) ON DELETE CASCADE
Ок. Нашел ошибку в структуре - там же связь многие ко многим постов и хэштегов.
Удалил лишнее поле с хештегом в таблице Posts и внешний ключ по хэштегу

2020-06-04 19:41 UTC, VikingBO requested changes
Оставленные комментарии нужно доработать плюс индекс ```role_title_idx``` явно не нужен по нашему ТЗ
И еще столбец ```posts.`hashtag` ``` явно излишний, у нас есть связующая таблица ```post_hashtags``` где внешние ключи связывают её с таблицами ```posts``` и ```hashtags```, обратной связи нам не требуется.

Общее замечание сводиться к тому что во всех таблицах связи и столбцы имеют совершенно разные названия, для связей лучше использовать название внешней таблицы и столбца на который указывает связь, например для связи поста с пользователем лучше использовать столбец ```user_id```, тогда это будет логически читаться проще и не будет путаницы при работе в дальнейшем, а сейчас можно чутка запутаться пытаясь прочитать связи.

2020-06-08 05:18 UTC, VikingBO approved these changes
Вроде всё поправили что нужно было

2020-06-08 05:19 UTC, merged