Created queries for adding info to database and fetching info from da…
htmlacademy-php/1418273-readme-12 pull request #8
Opened 2020-06-13 17:47 UTC by mikhail7275

…tabase

2020-06-16 12:27 UTC, VikingBO requested changes
В целом здорово, видно что ты не первый раз пишешь, но я бы обсудил некоторые решения или хотя бы хотел услышать обоснование.

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +INSERT content_types (title, icon_class_name)
Для соответствия стандартам стоит указывать после INSERT слово INTO, да это не указано как обязательное написание но это улучшает читабельность и в будущем будет меньше возможностей поймать ошибку при использовании SQL в других базах данных, поэтому лучше привыкать писать по стандартам сразу.

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +INSERT users (registration_date, email, login, password)
тоже стоит добавить INTO

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +INSERT posts (date_create, title, content, quote_author, image, user_id, content_type_id)
тоже стоит добавить INTO

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +INSERT comments (date_create, content, user_id, post_id)
тоже стоит добавить INTO

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +    (now(), 'name_email1@gmail.com', 'user_login1', 'user_password1'),
Здесь и ниже добавление NOW() для полей где указано по умолчанию CURRENT_TIMESTAMP не имеет смысла так как добавляет ту же самую метку.

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +INSERT subscriptions (author_user_id, subscription_user_id)
тоже стоит добавить INTO

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +INNER JOIN users AS u ON p.user_id = u.id
не совсем понял смысла подобного присоединения, для автоматической проверки наличия пользователя? Очень сомнительный JOIN с учетом увеличения, хоть и не критического на данном этапе, тяжести запроса. Сразу возникают вопросы по какой причине может возникнуть ситуация когда нам не нужно получать посты пользователя который был удален по какой-то причине из базы данных. Если пользователь был удален почему его посты остались в базе, если пользователь не удаляется физически, а просто в статусе удаленного почему его посты не нужно видеть? Если посты не должны быть видны почему не проверяется удален ли пользователь? Вообщем если возникнет вдруг ситуация когда понадобиться запросить посты несуществующего пользователя то это скорее вопрос плохой архитектуры и проверки наличия пользователя до запроса, а не во время. Хотя если у тебя есть другое видение я был бы рад обсудить.

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +        c.content AS `comment`,
интересно почему только тут ты решил выделить косыми кавычками наименование, хотя нигде до этого не делал подобного, сильно выбивается из общей картины :)

2020-06-16 12:27 UTC, VikingBO commented on quertes.sql
> +SELECT  p.date_create,
Нет, не понимаю, объясни логику запроса пожалуйста, зачем столько сложностей для получения нужных параметров, чем это оправдано?

2020-06-16 12:27 UTC, VikingBO commented on schema.sql
> +    `email` VARCHAR(50) NOT NULL,
Да, совершенно согласен, не помню почему оставил подобное количество без внимания но согласен с правкой, мы не можем знать насколько длинный у пользователя email или пароль, не уверен что 50 символов должно прям навсегда хватить но большинство вряд ли смогут превысить.

2020-06-16 14:15 UTC, mikhail7275 commented on quertes.sql
> +        c.content AS `comment`,
да, тут просто забыл)

2020-06-16 14:18 UTC, mikhail7275 commented on quertes.sql
> +INSERT content_types (title, icon_class_name)
Исправил

2020-06-16 14:18 UTC, mikhail7275 commented on quertes.sql
> +INSERT posts (date_create, title, content, quote_author, image, user_id, content_type_id)
Исправил

2020-06-16 14:18 UTC, mikhail7275 commented on quertes.sql
> +INSERT users (registration_date, email, login, password)
Исправил

2020-06-16 14:18 UTC, mikhail7275 commented on quertes.sql
> +INSERT comments (date_create, content, user_id, post_id)
Исправил

2020-06-16 14:18 UTC, mikhail7275 commented on quertes.sql
> +INSERT subscriptions (author_user_id, subscription_user_id)
Исправил

2020-06-16 14:18 UTC, mikhail7275 commented on schema.sql
> +    `email` VARCHAR(50) NOT NULL,
ок

2020-06-16 14:35 UTC, mikhail7275 commented on quertes.sql
> +    (now(), 'name_email1@gmail.com', 'user_login1', 'user_password1'),
да, исправил

2020-06-16 15:33 UTC, mikhail7275 commented on quertes.sql
> +INNER JOIN users AS u ON p.user_id = u.id
Посты увязаны с пользователями, то есть если нужен пост конкретного пользователя, то к информации о посте добавляем инфу по пользователю (логин), также с учетом условия по данному пользователю - исходя из цели запроса: Получить список постов для конкретного пользователя.

2020-06-16 15:36 UTC, mikhail7275 commented on quertes.sql
> +SELECT  p.date_create,
Раз необходимо получить список комментариев по посту с учетом информации по пользователю (логин), то увязал комментарии, посты и пользователей, по условию на идентификатор поста

2020-06-16 18:42 UTC, VikingBO commented on quertes.sql
> +INNER JOIN users AS u ON p.user_id = u.id
Это не объясняет почему мы вместо простой фильтрации по определенному p.user_id делаем JOIN таблицы user и делаем фильтрацию через неё
Что нам мешает делать просто фильтрацию по полю и зачем нам нужен u.login если нам нужны посты пользователя. а не данные о пользователе?

2020-06-16 18:43 UTC, VikingBO commented on quertes.sql
> +SELECT  p.date_create,
То же самое, что мешает просто фильтровать комментарии по полю post_id и присоединять только одну таблицу user для добавления его логина?

2020-06-16 18:45 UTC, VikingBO reviewed
Аргументация присоединения таблиц явно хромает, мы можем получать те же данные с меньшим количеством присоединений, тем более что по условиям запросы не обязаны содержать дополнительной информации. Сможешь более аргументированно обосновать лишние присоединения?

2020-06-17 06:15 UTC, mikhail7275 commented on quertes.sql
> +INNER JOIN users AS u ON p.user_id = u.id
Да, если учесть только саму постановку запроса, то информация будет лишней и JOIN не нужен. Сделал, для более полной информации по пользователю (логин)

2020-06-17 06:16 UTC, mikhail7275 commented on quertes.sql
> +SELECT  p.date_create,
Да, если учесть только саму постановку запроса, то информация будет лишней и JOIN не нужен. Сделал, для более полной информации по посту.

2020-06-17 10:15 UTC, VikingBO approved these changes

2020-06-17 10:16 UTC, merged